# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new QA Build to Testers"
  lane :qa do
    gradle(task: 'clean')
    bump_version_code()
    gradle(
      task: "bundle",
      build_type: "Debug",
      print_command: false
    )
    
    ###---
    ##- Option 1 - Firebase App Distribution
    ###---
    # https://firebase.google.com/docs/app-distribution/android/distribute-fastlane?apptype=apk
    # firebase_app_distribution(
    #   app: "1:451705007039:android:d8eb265918e34f59694f0a",
    #   android_artifact_type: 'AAB',
    #   android_artifact_path: 'app/build/outputs/bundle/debug/app-debug.aab',
    #   testers: "thadduval.lavud@gmail.com",
    #   release_notes: "Lots of amazing new features to test out!",
    #   service_credentials_file: 'test-track-364314-b563af9c795c.json'
    # )
  
    ###---
    ##- Option 2 - upload_to_play_store on internal testing track
    ###---
    
    # TODO
    # Step 1 ) Upload Build to S3
    # Step 2 ) Notify on Slack with https://github.com/cieslakdawid/fastlane-plugin-slack_upload?

  end

  lane :bump_version_code do
    path = '../app/build.gradle'
    re = /versionCode\s+(\d+)/ 
  
    s = File.read(path)
    versionCode = s[re, 1].to_i
    s[re, 1] = (versionCode + 1).to_s
  
    f = File.new(path, 'w')
    f.write(s)
    f.close
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    # gradle(task: "clean assembleRelease")

    gradle(task: 'clean')
    bump_version_code()

    signing_key = load_json(json_path: "signing-key.json")
    
    gradle(
      task: "bundle",
      build_type: "Release",
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => signing_key["store_file"],
        "android.injected.signing.store.password" => signing_key["store_password"],
        "android.injected.signing.key.alias" => signing_key["key_alias"],
        "android.injected.signing.key.password" => signing_key["key_password"],
      })

    upload_to_play_store
  end
end
